### ISSUE TITLE
How to see the test results on AV2 dataset?

### ISSUE THREAD

**Issue by OliverLeeyiyang** [HKUST-Aerial-Robotics/SIMPL#10]
Hi,

I am Yiyang. I am now trying to test your model on AV2 dataset.

However, when I tried to check the evaluation results, I noticed that your evaluator was somehow based on Argoverse API, which is not supported by my side. 

What's more, when I tried to run your script for visualization in test mode, I noticed that the ground truth was not plotted on it, may I ask why? And if I want to see the evaluation on the test set, what modification would be necessary?

Thanks in advance!

**Comment by MasterIzumi** [comment]
Hi @OliverLeeyiyang,

1. A simple solution is to install the Argoverse API if possible. The APIs of av1 and av2 will not conflict, so it is safe to have both of them. Otherwise, you can implement the evaluation part by yourself, and you can refer to https://github.com/ZikangZhou/QCNet/tree/main/metrics.

2. AV1 and AV2 do not provide the GT for the test split. You can only submit your file to the eval.ai for evaluation to get the result on the test set. I just noticed that I have not released the submission code. I will clean the code and release it in the near future.

**Comment by OliverLeeyiyang** [comment]
Thanks for the reply!

I understand now. Have a nice weekend! And hope to see your submission code soon!
