### ISSUE TITLE
Question about YawLoss

### ISSUE THREAD

**Issue by yenanjing** [HKUST-Aerial-Robotics/SIMPL#4]
Thanks for your wonderful work and code sharing. I would like to ask where the yaw loss mentioned in the paper is reflected in the code. I can't find it in the network output and loss function definition, looking forward to your answer. In addition, I am curious whether this loss function has a relatively large role in your experiment.

**Comment by MasterIzumi** [comment]
@yenanjing Thanks for your comments. Since there is no ground truth yaw angle in the Argo1 dataset, the current version does not contain this part. I am currently busy with some personal matters, sorry for the delay. The loss function for yaw angles will be released with the code for Argo2 dataset in the near future, hopefully within this month.

**Comment by MasterIzumi** [comment]
About the second question, in my personal experience, the introduction of yaw loss can improve the prediction performance for low-speed vehicles, avoiding some jerky trajectories. However, it does not influence very much on the overall official metrics.

**Comment by yenanjing** [comment]
Thank you for your timely reply and look forward to your future updates.

**Comment by MasterIzumi** [comment]
@yenanjing Hi, the code for Argo2 has been released. Please feel free to contact us if you have any questions.
